### ISSUE TITLE
Time outs when restarting Ergo

### ISSUE THREAD

**Issue by poVoq** [oragono/oragono-dnsbl#3]
When I restart Ergo I get a lot of such errors:

`couldn't check IP ban script : xxx.xxx.xxx.xxx : Operation timed out`

I assume this is because of some rate limit on their side?

Maybe the rate of reconnections / checks could be throttled somehow?

**Comment by slingamn** [comment]
What ban script are you using?

**Comment by poVoq** [comment]
Basically the defaults from this repo.

Edit: sorry, I accidentially closed this.

**Comment by slingamn** [comment]
Oh, sorry, I didn't see what repo this issue was posted in :-)

What's the underlying goal here? Do you want to avoid triggering upstream's rate limits (to be a good neighbor)? Do you want to speed up the reconnections? If there isn't enough capacity available to check the IP, do you want the reconnections to succeed or fail?

**Comment by poVoq** [comment]
Hard to say what the best option would be 😅

**Comment by slingamn** [comment]
If you're just using the default configuration from this repo, I would suggest that you might not need DNSBLs at all :-)

The default configuration here is really just an illustration of the available syntax, not a recommendation. Both ergo.chat and my personal server run without any DNSBLs, without any significant issues (every now and then I manually add a `UBAN REQUIRE-SASL` on some problem IP block).

I resisted adding DNSBLs directly in Ergo (instead opting for this external plugin model) because they reduce privacy and also robustness.

**Comment by poVoq** [comment]
Actually, see the PR I opened. Requiring SASL login for Tor users has been *very* helpful against some persistent trolls on our IRCd.

**Comment by poVoq** [comment]
Looks like `torexit.dan.me.uk` might be down right now, which could have been the original issue.
